### ISSUE TITLE
[BUG] UIHint = InputUIHints.VariablePicker not working in Studio

### ISSUE THREAD

**Issue by Nekrosis1** [elsa-workflows/elsa-studio#309]
When creating a custom activity with UIHint = InputUIHints.VariablePicker, although you get a dropdown to choose a variable, selecting a variable does nothing.
Either there is a bug or the feature is not implemented yet.
Built-in activities that use variables as in- or output use special implementation that cannot be used easily for custom activities.

**Comment by jdevillard** [comment]
Hello, 

some element was added recently to add a dropdown and select Variable Input (instead of litteral or scripting). The allow you to not use a UIHint and should work for any properties of you activities.

Have you take a look at https://github.com/elsa-workflows/elsa-studio/pull/274 for ui side and https://github.com/elsa-workflows/elsa-core/pull/5918 for server side implementation

Would this fit you need ?

**Comment by Nekrosis1** [comment]
Ah, so instead of using the UIHint VariablePicker on an Input, I can use the type Variable, similar to how it is used in the default activity SetVariable.
Yes, this is what I was looking for.
Thank you
