### ISSUE TITLE
[FEAT] Support Variables as Direct Activity Inputs Without Scripting

### ISSUE THREAD

**Issue by sNakiex** [elsa-workflows/elsa-studio#316]
Currently, retrieving data from a variable for use in an input field requires additional scripting. It would be beneficial to implement a more streamlined approach, similar to how we directly assign output to a variable.

This change would enhance both readability and usability.

Let me know if more information is required!

**Comment by jdevillard** [comment]
Hello ,

It should be already available .

You can take a look at #274 for ui side and https://github.com/elsa-workflows/elsa-core/pull/5918 for server side implementation 

These PR allow you to choose the variable component in the dropdown list (instead of script) and then choose the variable in a new dropdown.

**Comment by sNakiex** [comment]
Oh my apologies I totally overlooked these PR's. Thank you for the addition.
